import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.function.*;
import java.util.stream.Collectors;

//TIP To <b>Run</b> code, press <shortcut actionId="Run"/> or
// click the <icon src="AllIcons.Actions.Execute"/> icon in the gutter.
public class Main {
    public static void main(String[] args) {
        //TIP Press <shortcut actionId="ShowIntentionActions"/> with your caret at the highlighted text
        // to see how IntelliJ IDEA suggests fixing it.
        List<Integer> ints = Arrays.asList(5, 3, 25, 7, 63, 4, 73, 42, 72, 3, 64, 6, 0, -34, 2, -521, 32);
        List<String> strings = Arrays.asList("HELLO", "aPpLe", "WORLD", "carrot", "JAVA", "cow", "fig", "PROGRAMMING");
        List<Double> doubles = List.of(32.1, 2.76, 3.0, 1.45, 89.2);
        List<String> namesList = List.of("Mary", "Jane");
        List<Integer> ints2 = Arrays.asList(5, -3, 15, 7, 3);

        /*
         * 1. Use a Predicate to filter a list of integers, keeping only those that are
         * divisible by 3.
         */

        Predicate<Integer> divBy3 = (x) -> x % 3 == 0;// YOUR CODE - function that can be applied

        List<Integer> integers = ints.stream().filter(divBy3).toList();

        System.out.println("Input:" + ints);
        System.out.println("output:" + integers);
        System.out.println();

        /*
         * 2. Create a Function that takes a double and returns the whole number
         * portion.
         */
        Function<Double, Integer> intPart = (x) -> x.intValue();

        List<Integer> wholeParts = doubles.stream().map(intPart).toList();

        System.out.println("Input:" + doubles);
        System.out.println("Output: " + wholeParts);
        System.out.println();

        /* 3. Use a Consumer to print each string in a list in lowercase. */

       Consumer<String> printLowerCase = (str) -> System.out.println(str.toLowerCase());

       strings.forEach(printLowerCase);

        /*
         * 4. Write code that filters a list of integers to keep only those greater than
         * 50 and divisible by 3. Combine multiple predicates and resuse your predicate
         * from 1.
         */

        Predicate<Integer> greaterThanFifty = (x) -> x > 50;
        List newInts = ints.stream().filter(divBy3).filter(greaterThanFifty).toList();

        System.out.println(newInts);
        System.out.println();

        /*
         * 5.  Write code to square each number in a list of integers and then calculate the
         * sum of all squared values.
         */


        Function<Integer, Integer> sqrInts = (x) -> (int) Math.pow(x, 2);
        int sum = ints2.stream().map(sqrInts).collect(Collectors.summingInt(Integer::intValue));
        // or  int sum = ints2.stream().map(sqrInts).mapToInt(Integer::intValue).sum();

        System.out.println("Input:" + ints2);
        System.out.println("Output(Sum of squares): " + sum);
        System.out.println();

        /*
         *6. Write a function to add a prefix "Hello, " to a given string. Apply it to a
         * list of names.
         */

        Function<String, String> addPrefix = (str) -> "Hello " + str;
        System.out.println("Input:" + namesList);

        namesList.stream().map(addPrefix).forEach(System.out::println);

        /*
         * 7. Write a function that converts a number to its cube.
         * Write a function that converts a number to a string prefixed by "Result: ".
         * Chain these functions and
         * apply them to a list of numbers.
         */

        Function<Integer, Integer> cubeInt = (x) -> (int) Math.pow(x, 2);
        Function<Integer, String> addResultPrefix = (x) -> "Result: " + x;

        List<String> cubedInts = ints2.stream().map(cubeInt).map(addResultPrefix).toList();

        System.out.println("Input:" + ints2);
        System.out.println("Output (cubed and prefixed with Result): " + cubedInts);
        System.out.println();

        /**
         * 8. Write a Supplier to generate random integers between 1 and 100.
         * Call the supplier 10 times and create a list of the the generated values.
         */

        Supplier<Integer> generateRandomInt = () -> (int) (Math.random() * 100);

        ArrayList<Integer> intList = new ArrayList<>();
        
        for (int i = 0; i < 10; i++) {
            intList.add(generateRandomInt.get());
        }

        System.out.println("List generated by Supplier: " + intList);
        System.out.println();

        /**
         * 9.  Create a BiFunction that takes two strings
         * and returns their concatenation with a space in between.
         * Use it on pairs of strings.
         * https://docs.oracle.com/javase/8/docs/api/java/util/function/BiFunction.html
         */


        BiFunction<String, String, String> concatenateStrings = (str1, str2) -> str1 + " " + str2;

        System.out.println("Input: {Hello, Dear}");
        System.out.println("Output: " + concatenateStrings.apply("Hello", "Dear"));

        List <String> strList2 = List.of("Would", "this", "darkness", "ever", "lift?");

        String newStr = "";

        strList2.stream().forEach((str) -> concatenateStrings.apply(newStr, str));

        System.out.println("Input: " + strList2);
        System.out.println("Output: " + newStr);
        System.out.println();

        /**
         * 10. Write a method that takes a list of strings and a Predicate<String> as
         * arguments.
         * The method should return a new list containing only the strings that satisfy
         * the predicate. Test it with:
         * (a) Strings that start with "P",
         * (b) Strings longer than 4 characters.
         */

        //Your code
        Predicate<String> startsWithP = (str) -> str.indexOf("P") == 0;
        Predicate<String> greaterThanFourCharacters = (str) -> str.length() > 4;

        List<String> list3 = List.of("amy", "Peter", "Pam", "Paul", "Neela", "Porter");
        System.out.println("InputList: " + list3);

        List<String> list3Filtered = applyPredicate(list3, startsWithP);

        System.out.println("Filtered List: " + list3Filtered);

        list3Filtered = applyPredicate(list3, greaterThanFourCharacters);

        System.out.println("Filtered List: " + list3Filtered);
        System.out.println();

    }


    static List<String> applyPredicate(List<String> list, Predicate p) {
        return list.stream().filter(p).toList();
    }
}
